package ArduinoML.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class AnalogCondition_Constraints extends BaseConstraintsDescriptor {
  public AnalogCondition_Constraints() {
    super(MetaAdapterFactory.getConcept(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df271b69b0L, "ArduinoML.structure.AnalogCondition"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df271b69b0L, 0x6b9055df271f0412L, "cond"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df271b69b0L, 0x6b9055df271f0412L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "cond";
        return (SPropertyOperations.getString(propertyValue)).matches("<|>|==|<=|>=");
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df271b69b0L, 0x6b9055df271bf6d4L, "value"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df271b69b0L, 0x6b9055df271bf6d4L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "value";
        return (SPropertyOperations.getInteger(propertyValue)) < 1024;
      }
    });
    return properties;
  }
}
