package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptActuator = createDescriptorForActuator();
  /*package*/ final ConceptDescriptor myConceptAnalogCondition = createDescriptorForAnalogCondition();
  /*package*/ final ConceptDescriptor myConceptAnalogSensor = createDescriptorForAnalogSensor();
  /*package*/ final ConceptDescriptor myConceptApp = createDescriptorForApp();
  /*package*/ final ConceptDescriptor myConceptBrick = createDescriptorForBrick();
  /*package*/ final ConceptDescriptor myConceptCondition = createDescriptorForCondition();
  /*package*/ final ConceptDescriptor myConceptLogicalCondition = createDescriptorForLogicalCondition();
  /*package*/ final ConceptDescriptor myConceptLogicalSensor = createDescriptorForLogicalSensor();
  /*package*/ final ConceptDescriptor myConceptMode = createDescriptorForMode();
  /*package*/ final ConceptDescriptor myConceptReachable = createDescriptorForReachable();
  /*package*/ final ConceptDescriptor myConceptSensor = createDescriptorForSensor();
  /*package*/ final ConceptDescriptor myConceptSignalTransition = createDescriptorForSignalTransition();
  /*package*/ final ConceptDescriptor myConceptState = createDescriptorForState();
  /*package*/ final ConceptDescriptor myConceptTimedTransition = createDescriptorForTimedTransition();
  /*package*/ final ConceptDescriptor myConceptTransition = createDescriptorForTransition();
  /*package*/ final EnumerationDescriptor myEnumerationSIGNAL = new EnumerationDescriptor_SIGNAL();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActuator, myConceptAnalogCondition, myConceptAnalogSensor, myConceptApp, myConceptBrick, myConceptCondition, myConceptLogicalCondition, myConceptLogicalSensor, myConceptMode, myConceptReachable, myConceptSensor, myConceptSignalTransition, myConceptState, myConceptTimedTransition, myConceptTransition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.Actuator:
        return myConceptActuator;
      case LanguageConceptSwitch.AnalogCondition:
        return myConceptAnalogCondition;
      case LanguageConceptSwitch.AnalogSensor:
        return myConceptAnalogSensor;
      case LanguageConceptSwitch.App:
        return myConceptApp;
      case LanguageConceptSwitch.Brick:
        return myConceptBrick;
      case LanguageConceptSwitch.Condition:
        return myConceptCondition;
      case LanguageConceptSwitch.LogicalCondition:
        return myConceptLogicalCondition;
      case LanguageConceptSwitch.LogicalSensor:
        return myConceptLogicalSensor;
      case LanguageConceptSwitch.Mode:
        return myConceptMode;
      case LanguageConceptSwitch.Reachable:
        return myConceptReachable;
      case LanguageConceptSwitch.Sensor:
        return myConceptSensor;
      case LanguageConceptSwitch.SignalTransition:
        return myConceptSignalTransition;
      case LanguageConceptSwitch.State:
        return myConceptState;
      case LanguageConceptSwitch.TimedTransition:
        return myConceptTimedTransition;
      case LanguageConceptSwitch.Transition:
        return myConceptTransition;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationSIGNAL);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Action", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685faL);
    b.class_(false, false, false);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/4335307747509044730");
    b.version(2);
    b.property("value", 0x3c2a1b6d4a4685fdL).type(MetaIdFactory.dataTypeId(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685f5L)).origin("4335307747509044733").done();
    b.associate("actuator", 0x3c2a1b6d4a468601L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685f4L).optional(false).origin("4335307747509044737").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActuator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Actuator", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685f4L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Brick", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685e1L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/4335307747509044724");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnalogCondition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "AnalogCondition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df271b69b0L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Condition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x7c71bdff0dc570e5L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/7750789375626799536");
    b.version(2);
    b.property("value", 0x6b9055df271bf6d4L).type(PrimitiveTypeId.INTEGER).origin("7750789375626835668").done();
    b.property("cond", 0x6b9055df271f0412L).type(PrimitiveTypeId.STRING).origin("7750789375627035666").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnalogSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "AnalogSensor", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df271951bbL);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Sensor", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685f3L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/7750789375626662331");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "App", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685d7L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/4335307747509044695");
    b.version(2);
    b.associate("initial", 0x3c2a1b6d4a4685edL).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x49f3ae9b88635758L).optional(false).origin("4335307747509044717").done();
    b.aggregate("bricks", 0x3c2a1b6d4a4685e8L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685e1L).optional(false).ordered(true).multiple(true).origin("4335307747509044712").done();
    b.aggregate("modes", 0x49f3ae9b88638732L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x49f3ae9b88635758L).optional(false).ordered(true).multiple(true).origin("5328794767140816690").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBrick() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Brick", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685e1L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/4335307747509044705");
    b.version(2);
    b.property("pin", 0x3c2a1b6d4a4685f1L).type(PrimitiveTypeId.INTEGER).origin("4335307747509044721").done();
    b.property("watch", 0x35ee97acc8ff7c9L).type(PrimitiveTypeId.BOOLEAN).origin("242888143551854537").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCondition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Condition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x7c71bdff0dc570e5L);
    b.class_(false, true, false);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/8967157236216721637");
    b.version(2);
    b.associate("sensor", 0x7c71bdff0dc570e8L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685f3L).optional(false).origin("8967157236216721640").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLogicalCondition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "LogicalCondition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df271b69b3L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Condition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x7c71bdff0dc570e5L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/7750789375626799539");
    b.version(2);
    b.property("value", 0x6b9055df271bf6d2L).type(MetaIdFactory.dataTypeId(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685f5L)).origin("7750789375626835666").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLogicalSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "LogicalSensor", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x6b9055df27195156L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Sensor", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685f3L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/7750789375626662230");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Mode", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x49f3ae9b88635758L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Reachable", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x49f3ae9b886ce6d0L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/5328794767140804440");
    b.version(2);
    b.associate("initial", 0x49f3ae9b8863577eL).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685daL).optional(false).origin("5328794767140804478").done();
    b.aggregate("states", 0x49f3ae9b88671f25L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685daL).optional(false).ordered(true).multiple(true).origin("5328794767141052197").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReachable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Reachable", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x49f3ae9b886ce6d0L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/5328794767141430992");
    b.version(2);
    b.aggregate("actions", 0x3c2a1b6d4a468603L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685faL).optional(true).ordered(true).multiple(true).origin("4335307747509044739").done();
    b.aggregate("timedTransition", 0x49f3ae9b88635781L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x763d572dd5e42d08L).optional(true).ordered(true).multiple(false).origin("5328794767140804481").done();
    b.aggregate("signalTransitions", 0x49f3ae9b88635782L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x763d572dd5e42763L).optional(true).ordered(true).multiple(true).origin("5328794767140804482").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Sensor", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685f3L);
    b.class_(false, true, false);
    b.super_("ArduinoML.structure.Brick", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685e1L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/4335307747509044723");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSignalTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "SignalTransition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x763d572dd5e42763L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Transition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a468605L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/8520061924428490595");
    b.version(2);
    b.aggregate("conditions", 0x7c71bdff0dc570f2L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x7c71bdff0dc570e5L).optional(true).ordered(true).multiple(true).origin("8967157236216721650").done();
    b.alias("signal transition");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForState() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "State", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a4685daL);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Reachable", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x49f3ae9b886ce6d0L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/4335307747509044698");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTimedTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "TimedTransition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x763d572dd5e42d08L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Transition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a468605L);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/8520061924428492040");
    b.version(2);
    b.property("delay", 0x763d572dd5e42d09L).type(PrimitiveTypeId.INTEGER).origin("8520061924428492041").done();
    b.alias("timed transition");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Transition", 0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x3c2a1b6d4a468605L);
    b.class_(false, true, false);
    b.origin("r:248d02e4-0fe5-41e2-9652-fc52d3b7237a(ArduinoML.structure)/4335307747509044741");
    b.version(2);
    b.associate("next", 0x3c2a1b6d4a468606L).target(0x6d5f556878454ac1L, 0xba976d57e4d58942L, 0x49f3ae9b886ce6d0L).optional(false).origin("4335307747509044742").done();
    return b.create();
  }
}
